### ISSUE TITLE
Resource editor bugs

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#149]
I think I heard you mention there's one bug on mac, not sure if it's included in these two:

1. Images for spawns `spawn.png` and teles `tele.png` fail to load 100% of the time. Image files are there.

2. Not sure if this is a bug or simply not yet included: when I click to open a resource file, it starts in my home directory, and I have to navigate all the way to chimsockets. Any way to make it start in the current directory, or even `resources/editor`?

**Comment by evanw555** [comment]
Use `Resource Editor (Windows).cmd` or `Resource Editor (Max, Linux)` to use the editor.
