### ISSUE TITLE
Small changes to file structure

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#153]
The game client code in `game` should not be on the same level as the static `home`, `about`, etc pages. We could 1) move them to the `static` folder on the top level, or 2) keep them in the `client` folder but nest them in a `pages` or `static` folder within `client`.

Ye?

**Comment by evanw555** [comment]
So you're saying the game code shouldn't be in the same place as the webpages? Makes sense, but if we move it all to `static`, then wouldn't we have to move all js files to `static` to be consistent?

Also, your new prof is sketch.

**Comment by davidvorona** [comment]
I'll buy you a bag of hot cheetos if you can remember what picture it's originally from.

I think folders `home`, `about`, and `signup` should be moved to a folder called `pages` or something within `client`.
