### ISSUE TITLE
Add "Meet the Team" page

### ISSUE THREAD

**Issue by evanw555** [Brethren-Studios/chimsockets#21]
@jaba9531 will develop a _Meet the Team_ page with photos and bios of each of us. Home page should link to it, and the page should link back to the home. You may add other cute stuff (e.g. job applications for interns) if you'd like.

@davidvorona @rickfoop @jaba9531 @evanw555 will all need to submit their bio and photo (if supported) on this issue thread.

**Comment by evanw555** [comment]
My bio:

> Evan Williams is a soon-to-be graduate of UC Berkeley with a B.A. in Computer Science. He is the lead designer of _Age of Chim_ and is the owner of the _Age of Chim_ domain and application server. His responsibilities include client- and server-side application development, development workflow construction, game design, lore and content contribution, and providing some of the game's graphics, among other things. He enjoys agile workflows, deep lore, decline bench, _Old School Runescape_, GameCube, Bush Beans, _Family Guy_, fly hats, freestyle runs, and a cold Coors Light.

**Comment by rickfoop** [comment]
My Bio:

Richard Ridley is a 2017 graduate of Stanford University with a B.S.  in Computer Science and minor in Economics. He is a recent addition to the _Age of Chim_ team and his primary responsibilities will include server-side development and algorithm design as well as providing vibes and contributing to discussions about game design. He is an avid consumer of _Coor's Light_, _Five Guy's Burgers and Fries_, and baked potatoes. In his free time, he enjoys training agility in _Old School Runescape_, watching _Game of Thrones_, and solving crossword puzzles.

**Comment by davidvorona** [comment]
My Bio:

David Vorona is a graduate of the University of Virginia, where he was a student of Economics and the Russian language. Initially a hobby, programming now takes up most of his time, and his prime directives on the *Age of Chim* include web development across the stack, overall game design, and content creation. He is a common fixture at the local *Wingstop*, and is universally admired for his freestyling prowess and quest cape in *Old School Runescape*.
