### ISSUE TITLE
Hook up account page to account API and implement changeEmail and changePassword middleware

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#225]
Replace dummy `changeEmail` and `changePassword` with fully implemented methods.

Consider any other necessary fields the `user_accounts` table needs.

**Comment by evanw555** [comment]
@davidvorona is this done? should we make a newer, more specific ticket?

**Comment by davidvorona** [comment]
We should change it to: 'hook up account page to accounts api and finish `changeEmail` and `changePassword` middleware.

**Comment by evanw555** [comment]
Agreed.

**Comment by davidvorona** [comment]
Closed in #286
