### ISSUE TITLE
Improve queries on friend tables

### ISSUE THREAD

**Issue by evanw555** [Brethren-Studios/chimsockets#233]
Currently, `friends.js` makes multiple queries in order to do all friend request and friend operations which include inefficiencies such as:
- making multiple independent queries for things that can be done in a single query (e.g. querying for user keys, then querying for corresponding friend tables).
- making multiple sequential queries (e.g. querying for user keys, then making subsequent query in callback for first query)

Fix this by making all friend operations single queries. Make use of joins in order to find friend data given only usernames.

**Comment by davidvorona** [comment]
So this only matters for add/delete friend/friendRequest, since every other `friends.js` query uses a join already. My only concern is that we need to be able to tell if the friend someone is trying to add/request actually exists. Separating `getUsers` makes this easy, so make sure if you use a join that you're able to programmatically check if the reason for the failure is a non-existing user.

**Comment by evanw555** [comment]
You're right, but moreover I think having a separate function for `getUsers` in itself isn't ideal, because this doesn't seem to make sense as part of the `friends.js` interface. But regardless as part of this issue we should critically examine the queries we've written so far.

**Comment by davidvorona** [comment]
Yeah, regardless of whether or not we remove `getUsers`, and if we can we should, it should be imported in from a `user` file or something.

That makes me think, we should probably remove the actual SQL queries from `auth.js` and `account.js` too. These should have their own files in `db`, organized by table, and then should be imported into `auth.js` or `account.js`. These files should really only handle at a higher level how the server API responds to a registration/auth request.

**Comment by rickfoop** [comment]
I was actually about to make an issue about this. I feel like anything issuing db queries should live within the `db` directory.

I don't know if I agree with having every table having their own `.js` if they're going to be directly used by clients.  This might not be as useful as intended, as for example `auth.js` might still have to manage transaction state.

It might be more useful to abstract sets of tables into meaningful services. Ex: `auth_service` or `account_service`.
