### ISSUE TITLE
Set up testing suite

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#241]
Chimsockets is sorely in need of tests.

[Mocha](https://mochajs.org/) is a popular open-source testing framework for Node.js. Combined with [Chai](http://www.chaijs.com/), Mocha will run all of our tests for the web app. There are a few other good assertion libs, but the syntax differences are arbitrary and Chai.js has the most pleasing name.

We have a few options as to how we organize, but I think the following is the best way:

Name test files with the `.tests` convention between the `fileName` and the extension. Example: `namespace.tests.js`. It exists at the same directory level as the file it's testing.

This encourages TDD, makes imports easier, and makes for a quicker reference. While it bloats subdirectories, the naming convention ensures files and their tests are always next to each other and obviously related while still looking categorically different.

The majority of this ticket will be configuring and setting up our testing process, but this should also include some real tests for each method in `auth.js`. Tests should run in both the browser and node, and be configured for an IDE as well.

**Comment by evanw555** [comment]
Closed by #253
