### ISSUE TITLE
Dungeon completion overlay not showing up when state is saved in a dungeon

### ISSUE THREAD

**Issue by evanw555** [Brethren-Studios/chimsockets#256]
How to reproduce:
- enter a dungeon
- while in the dungeon, exit so that the user's state is saved
- log back in, you should start in the dungeon again
- finish the dungeon by stepping on the ladder, the overlay should fail to appear on the client

Preliminary debugging:
- all server-side operations seem to be functioning as normal
  - `dungeon-complete` socket message is being sent to the client
- client receives the `dungeon-complete` socket message, but fails to open the overlay

**Comment by davidvorona** [comment]
Fixed in PR #274
