### ISSUE TITLE
Commit Table Schemas to Repository

### ISSUE THREAD

**Issue by rickfoop** [Brethren-Studios/chimsockets#277]
We should commit our Table Schemas to this repository. This can be a safeguard for manual mistakes, and could be useful for testing. (Ex: Tests constructing in-memory db tables instead of talking to possibly changing production or test databases).

This should be pretty easy to do. As far as where they should go, maybe: resources/sql/${TABLE_NAME}_seed.sql

An example seed file would contain the SQL command necessary to create a table as it currently exists in our DB.

**Comment by davidvorona** [comment]
I'll do this since I made most of them
