### ISSUE TITLE
Connect Homepage to sign-in script, continue front-end dev

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#41]
1. Move from `/home` to `/` route.
2. Sign-in button should reveal (some sort of simple animation) the two input forms for username and password as well as a Play Now button.
3. Sign-up form should continue to redirect to another page, though that page should be improved.
4. Dev blog page should be added (or maybe link to a 3rd party blog service/github)
5. Add titles to pages (i.e. text that shows up on the tab)

**Comment by evanw555** [comment]
Removed bullet "Add team page", as that is handled by #21
