### ISSUE TITLE
Add shared constants file

### ISSUE THREAD

**Issue by evanw555** [Brethren-Studios/chimsockets#43]
There are some constants (e.g. map dims, room ID prefixes) that are used by both the client and the server. It is bad practice to hard-code values throughout the codebase, as well as to keep two separate sets of constants.

This will be solved by having one single file `constants.js` that will be used by the `/play` page as well as by the server using npm.

**Comment by rickfoop** [comment]
Good issue. I agree. Some of my comments in my code referenced this problem, and I can remove them once this issue is resolved.
