### ISSUE TITLE
Sign up for Age of Chim page, logout functionality, extended tokens

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#47]
1. On successful account creation, redirect to home page, where player clicks Play Now, logs in, and starts playing.

2. Add an option to log in and not play on the home page, and of course sign up doesn't redirect to play, it takes to the home page.

3. Add logout functionality.

4. Don't remove token unless user logs out or leaves our website.

**Comment by davidvorona** [comment]
There's a few ways we could go about designing auth on our website. Major questions:

1. Do we want the user to be able to log in and surf the site (not necessarily play the game) as a particular user? Pros: This opens up the possibility for user-specific statistics,  account settings, etc. Probably necessary tbh. Cons: token would have to persist. Maybe give it an expiration and if the user tries to play the game or access his account settings after it expires, make him log in again.

2. Do we want the user to be able to leave the site (still logged in), and come back and still be logged in? Pros: ease of access. Cons: cookies, which can be insecure.

In general, it might be smart to lock some more dangerous account settings (delete account, change password, etc.) behind an extra login, just in case.

3. If the user logs out of the game, does he log out of his account? What is the relationship between accounts and game clients. Can a player have one account, with multiple characters, playing on clients?

**Comment by evanw555** [comment]
I agree with everything in this thread, except we need to make sure that if a user navigates from `/play` to `/` without logging out, the player must still be removed from the game instance, even though the player is technically logged in. I know this sounds basic, but I can foresee us running into that without thinking about it.

**Comment by davidvorona** [comment]
Player should be removed from the game instance anyways because the room/game objects are only actually modified in the socket logic, which is predicated on the player be connected.
