### ISSUE TITLE
Input to handleUserInput Function should be changed to allow for custom inputs and more dynamic handling.

### ISSUE THREAD

**Issue by rickfoop** [Brethren-Studios/chimsockets#51]
As of now, the handleUserInput function is structured to handle string inputs, and as of now uses switch statements to operate on those inputs. 

I propose changing the handleUserInput function to instead operate on a UserInput object type which would contain at least two fields - (type, and data). 

This would allow for more dynamic responses to user Input and would allow for more code modularity.

Example user inputs could be 
{type:"movement", data:"right"}
{type:"rotation", data:"right}
{type:"use-item", data:"2"}

Proposed handleUserInput function would resemble:

```
switch(userInput.type):
  case 'movement':
    return handleUserMovement(userInput.data);
  case 'rotation':
    return handleUserRotation(userInput.data);
  case 'use-item':
    return handleUseItem(userInput.data);
   default:
     return false;

```

**Comment by evanw555** [comment]
Good issue. Just for some technical context, I've added the following info on the user input end-to-end technical flow:

https://github.com/Brethren-Studios/chimsockets/wiki/User-Input

**Comment by evanw555** [comment]
@rickfoop Gonna close this manually. In order for the #X markup to work, you must type `closes #X` or `fixes #X` (or some other words, google it) in the **PR description**. In the future, don't include any reference numbers in any commit messages or issue/PR titles, it looks beats.

**Comment by rickfoop** [comment]
Ok sounds good, will do it in the future. Sorry for not reading your workflow guide.
