### ISSUE TITLE
Add private messaging functionality

### ISSUE THREAD

**Issue by rickfoop** [Brethren-Studios/chimsockets#58]
In conjunction with a basic chat system, I'd like to implement a private messaging functionality.

There are two possible ways that I envision doing this:
1. Broadcasting private messages to the rooms in which the intended recipient currently resides, but only operating on those broadcasts if the current user is the intended user.

This approach might be inefficient, but doesn't require any additional framework.

2.  Directly sending private messages to their user's sockets. 

The approach would require maintaining a dictionary that would map usernames to their socket id within the server code. To send private messages, users would broadcast a send private message message to the server which would include an intended user and message data. The server would then broadcast the message to the room unique to the user specified.

Alternatively, we could change socket's id's to be equal to their username.

Making a framework for this would be useful for future features: room invites, clan invites, aid requests, etc.

**Comment by evanw555** [comment]
Did some research, idk if changing a socket's native ID is necessarily a good idea. Best option may be to map usernames to socket IDs (or to socket objects themselves). You are right though, it may be a good idea to refactor the server side socket logic and maybe make some abstractions ourselves.

Also, we need to watch out for a known bug when dealing with this; I know that currently, a user can authenticate and open two separate client windows. This results in one single user loaded on the server, yet two separate socket connections. We should deal with this, I will open a ticket.
