### ISSUE TITLE
Add Friends Functionality

### ISSUE THREAD

**Issue by rickfoop** [Brethren-Studios/chimsockets#59]
In conjunction with private messaging, and in the style of Runescape, our game should include a system for interacting with friends.

Basic functionality would include:
-Adding and removing friends
  -Initially through a dynamic text field -but perhaps later through right clicking on graphic entities.
-An easy way to private message your friends

Will this is possibly a low priority, as we're figuring out game mechanics, it could be a cool thing to add.

**Comment by davidvorona** [comment]
Now that a very basic private messaging GUI has been added, it's a good time to start working on the friends feature.

Friend relationships would be kept in a PG table, which would most likely be two columns, the first a user_id and the second a friend_id (just a user_id but a reference to another user_id in the user table).

**Comment by evanw555** [comment]
@davidvorona This is dope. Given that we already have the framework to easily check if a user is online, we should consider having the UI display whether a friend is online or offline.
