### ISSUE TITLE
Readme does not include any Runescape references.

### ISSUE THREAD

**Issue by rickfoop** [Brethren-Studios/chimsockets#8]
As indicated, our publicly facing ReadMe does not yet contain any references to Jagex's classic MMORPG Runescape. As ChimSockets draws upon its influences while also seeking to act as its technical and cultural successor, it is necessary for us to acknowledge the game within all outwardly facing materials.

**Comment by davidvorona** [comment]
Great suggestion Mr. Foop. Excited to see the work you'll do here at Brethren Studios, you're a valued member of our team!

**Comment by evanw555** [comment]
Solved by PR #9
