### ISSUE TITLE
Question about gamestate methods?

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#87]
How do we wanna go about using these methods in the future? Right now they're only accessible in `main.js`, where we init the class. I need to access these functions from other front-end components, and there's a few ways to do this. Let me know if none of this makes sense or if you see an obvious drawback.

1. Make `ClientGameState` a collection of methods we can pass around and make `init()` a method we call explicitly in `main.js`.

2. Just init the `ClientGameState` in gamestate.js and export the methods, `init()` will fire as soon as it's imported (see `webpack`) into `main.js` (effectively the same as what's happening now).

3. ??

**Comment by evanw555** [comment]
The `ClientGameState` object is just an object, so we can pass it by reference to your React components, right? And both of them can have a variable they can use that points to the same js object

**Comment by davidvorona** [comment]
Right, bout how do we access those methods without calling `init()`? What am I missing here?

**Comment by evanw555** [comment]
`init()` is called when the module (which is a function) is called (as `ClientGameState()`), what is returned from that call (`gameState`) is an object that has its own scope (private data) as well as public methods. So long as `ClientGameState()` is called once, then after the resulting object is passed around, all accesses to the object and its methods will be for the one object instance.

**Comment by davidvorona** [comment]
Right, that I understand. My problem has more to do with how webpack is implemented.

Imma just play around with it for a while.

**Comment by evanw555** [comment]
Ok. Let me know what you find.
